-- Chargeback baseline rates by month
-- Mode report: https://app.mode.com/xxx/reports/yyy
-- Query token: q1

SELECT
    DATE_TRUNC('month', CREATED_AT) AS MONTH
    , COUNT(CASE WHEN IS_CHARGEBACK = TRUE THEN 1 END) AS CHARGEBACKS
    , COUNT(*) AS TOTAL_TRANSACTIONS
    , CHARGEBACKS / NULLIF(TOTAL_TRANSACTIONS, 0) AS CHARGEBACK_RATE
FROM APP_PAYMENTS.PUBLIC.TRANSACTIONS
WHERE CREATED_AT >= '2025-01-01'
    AND TRANSACTION_TYPE = 'DOMESTIC'
GROUP BY 1
ORDER BY 1
